### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by frankbenoit** [esensar/neovim-java#141]
Hi

I try to get started with this API.

````
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Tester</groupId>
  <artifactId>Tester</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>21</release>
        </configuration>
      </plugin>
    </plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.ensarsarajcic.neovim.java</groupId>
			<artifactId>neovim-api</artifactId>
			<version>0.5.0</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.36</version>
		</dependency>
  </dependencies>
</project>
````

````
package test;

import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import com.ensarsarajcic.neovim.java.api.NeovimApi;
import com.ensarsarajcic.neovim.java.api.NeovimApis;
import com.ensarsarajcic.neovim.java.corerpc.client.ProcessRpcConnection;
import com.ensarsarajcic.neovim.java.corerpc.client.RpcClient;
import com.ensarsarajcic.neovim.java.corerpc.client.RpcStreamer;

public class Tester {

	public static void main(String[] args) throws Exception {
		RpcStreamer client = RpcClient.getDefaultAsyncInstance();

		ProcessBuilder pb = new ProcessBuilder("nvim", "--embed", "--clean");
		var neovim = pb.start();
		try(var neovimConnection = new ProcessRpcConnection(neovim, true)) {
			client.attach(neovimConnection);
			var api = NeovimApis.getApiForConnection(neovimConnection);
			actions(api);
        	}
        	client.stop();
	}

	private static void actions(NeovimApi api) {
		try {
			var info = api.getApiInfo()
					.get(5, TimeUnit.SECONDS);
			System.out.println("Info: "+info.getFunctions().stream()
					.map(a -> a.getName())
					.limit(5)
					.collect(Collectors.joining(", ")));

			var line = api.getCurrentLine()
					.get(1, TimeUnit.SECONDS);
			System.out.println("Line: "+line);

		} catch( Exception e ) {
			e.printStackTrace();
		}
	}
}
````

I observe a timeout exception in the first API call. I tried various `sleep()` calls in case nvim does take some startup time.

````
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.PackStream - Attaching PackStream to: ProcessRpcConnection{process=Process[pid=18240, exitValue="not exited"], killProcessOnClose=true}
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.AsyncRpcSender - Attached to output stream!
[pool-1-thread-1] INFO com.ensarsarajcic.neovim.java.corerpc.client.BackgroundRpcListener - Started listening on stream
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.PackStream - Attaching PackStream to: ProcessRpcConnection{process=Process[pid=18240, exitValue="not exited"], killProcessOnClose=true}
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.AsyncRpcSender - Attached to output stream!
[pool-1-thread-2] INFO com.ensarsarajcic.neovim.java.corerpc.client.BackgroundRpcListener - Started listening on stream
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.PackStream - Registered a new request callback: com.ensarsarajcic.neovim.java.corerpc.reactive.ReactiveRpcStreamerWrapper$$Lambda/0x0000028d010a39f0@2c039ac6
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.PackStream - Registered a new notification callback: com.ensarsarajcic.neovim.java.corerpc.reactive.ReactiveRpcStreamerWrapper$$Lambda/0x0000028d010a64b8@58c1670b
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.ProcessRpcConnection - Closing process connection. Killing process = true
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.PackStream - Stopping resources
[main] INFO com.ensarsarajcic.neovim.java.corerpc.client.BackgroundRpcListener - Stopped listening on stream
Exception in thread "main" java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at test.Tester.main(Tester.java:23)
````
Can you please help?

Another thing, i see this library did not receive updates since a while. Do you see this as a problem when starting a neovim integration?

**Comment by frankbenoit** [comment]
I think I figured it out

**Comment by esensar** [comment]
Thanks for reporting this.

The project was moved to [Codeberg](https://codeberg.org/neovim-java/). True, it was not updated in a while, but as far as I know, the only downside is missing newest API functions. That could easily be updated though (and it is also possible to make direct calls with `core-rpc` module, but that requires inspecting neovim API, to figure out how exactly to call it).

Do you intend to build a plugin or some other kind of integration? If you are planning on building a plugin, take a look at the [example plugin project](https://codeberg.org/neovim-java/neovim-http-api-plugin).

**Comment by frankbenoit** [comment]
Ok, just now learned about Codeberg, nice.

I am checking the possibilities for an Eclipse integration. No big chance I really start this effort.
However, there is Vrapper (Vim emulation) - certainly with many limitations - and I am really impressed by vscode-neovim and dream about this in my working environmen.

**Comment by esensar** [comment]
That should be doable I think. I initially wanted to do similar for JetBrains editors, but they have a pretty good vim emulation, so I gave up.

I would gladly help you out in your project.
